import './globals.css'
import type {Metadata} from 'next'
import {Navbar} from "@/components/composite/Navbar";
import {AuthProvider} from "@/providers/AuthProvider";

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
        <body>
        <AuthProvider>
            <Navbar/>
            {children}
        </AuthProvider>
        </body>
        </html>
    )
}
